services:
    dynamodb:
        container_name: dynamodb-local
        image: amazon/dynamodb-local
        command: -jar DynamoDBLocal.jar -sharedDb -dbPath . -optimizeDbBeforeStartup
        volumes:
            - dynamodb:/home/dynamodblocal
        ports:
            - 8000:8000
    dynamodb-admin:
        image: aaronshaf/dynamodb-admin 
        tty: true 
        ports: 
            - 8001:8001
        depends_on:
            - dynamodb 
        environment: 
            DYNAMO_ENDPOINT: http://dynamodb-local:8000
volumes:
    dynamodb:
        driver: local